services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  redis:
    image: redis:7.2-alpine
    container_name: redis_payment
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
#    container_name: elasticsearch
#    environment:
#      - node.name=es-node
#      - discovery.type=single-node
#      - xpack.security.enabled=false  # 간단하게 하기 위해 보안 비활성화
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    ports:
#      - "9200:9200"
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.12.0
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.12.0
#    container_name: logstash
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#    ports:
#      - "5000:5000"
#    depends_on:
#      - elasticsearch
volumes:
  redis_data: